### ISSUE TITLE
Rmpi compilation silently fails with R-3.4.0

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#4642]
I tried several times to build `R-3.4.0` unaltered, and it hung at `Rmpi` each time.

It could be something wrong with my `Intel MPI` setup, but other simple MPI jobs succeed, and `GROMACS` in this toolchain runs normally too.

**Comment by reedts** [comment]
Same issue on our cluster. Any `Intel MPI` related modules run just fine so I don't think our MPI setup is bugged.

**Comment by boegel** [comment]
@verdurin @reedts How is the `Rmpi` build hanging exactly? Can you give on overview of running/hanging processes, and maybe check with strace on the hanging process?

**Comment by verdurin** [comment]
Here's the last entry in the logs for me:
```
== 2017-05-30 16:38:41,321 run.py:488 DEBUG Using default regular expression: (?<![(,-]|\w)(?:error|segmentation fault|failed)(?![(,-]|\.?\w)
== 2017-05-30 16:38:41,322 rpackage.py:199 DEBUG Installing R package Rmpi version 0.6-6.
== 2017-05-30 16:38:41,322 rpackage.py:129 DEBUG make_cmdline_cmd returns R CMD INSTALL /camp/apps/eb/tmp/Rmpi/sources/r/R/extensions/Rmpi_0.6-6.tar.gz  --configure-args="--with-Rmpi-include=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/include64 --with-Rmpi-libpath=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/lib64 --with-mpi=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27 --with-Rmpi-type=INTELMPI"  --library=/camp/apps/eb/tmp/Rmpi/software/R/3.4.0-intel-2017a-X11-20170314/lib64/R/library --no-clean-on-error
== 2017-05-30 16:38:41,322 run.py:137 DEBUG run_cmd: running cmd R CMD INSTALL /camp/apps/eb/tmp/Rmpi/sources/r/R/extensions/Rmpi_0.6-6.tar.gz  --configure-args="--with-Rmpi-include=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/include64 --with-Rmpi-libpath=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/lib64 --with-mpi=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27 --with-Rmpi-type=INTELMPI"  --library=/camp/apps/eb/tmp/Rmpi/software/R/3.4.0-intel-2017a-X11-20170314/lib64/R/library --no-clean-on-error (in /camp/home/huffmaa)
== 2017-05-30 16:38:41,322 run.py:162 INFO running cmd: R CMD INSTALL /camp/apps/eb/tmp/Rmpi/sources/r/R/extensions/Rmpi_0.6-6.tar.gz  --configure-args="--with-Rmpi-include=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/include64 --with-Rmpi-libpath=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27/lib64 --with-mpi=/camp/apps/eb/intel-2017a/software/impi/2017.1.132-iccifort-2017.1.132-GCC-6.3.0-2.27 --with-Rmpi-type=INTELMPI"  --library=/camp/apps/eb/tmp/Rmpi/software/R/3.4.0-intel-2017a-X11-20170314/lib64/R/library --no-clean-on-error
```

The running process is:
```
[huffmaa@ca056 ~]$ cat /proc/4711/cmdline
/camp/apps/eb/tmp/Rmpi/software/R/3.4.0-intel-2017a-X11-20170314/lib64/R/bin/exec/R--no-save--slave
```
and there's this in the standard input
```
tools:::.test_load_package('Rmpi', '/camp/apps/eb/tmp/Rmpi/software/R/3.4.0-intel-2017a-X11-20170314/lib64/R/library')
```
`strace` doesn't show anything

**Comment by verdurin** [comment]
Not sure yet whether this is related, but I'm seeing an error with `Theano` too, this time at the sanity check stage:
```
== 2017-05-30 17:08:16,336 run.py:137 DEBUG run_cmd: running cmd /camp/apps/eb/intel-2017a/software/Python/2.7.13-intel-2017a/bin/python -c "import theano" (in /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13)
== 2017-05-30 17:08:16,336 run.py:162 INFO running cmd: /camp/apps/eb/intel-2017a/software/Python/2.7.13-intel-2017a/bin/python -c "import theano"
```

Here's what the process has open:
```
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 3 -> /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13/lib/python2.7/site-packages/Theano-0.9.0-py2.7.egg/theano/__init__.py
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 4 -> /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13/lib/python2.7/site-packages/Theano-0.9.0-py2.7.egg/theano/scan_module/__init__.py
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 5 -> /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13/lib/python2.7/site-packages/Theano-0.9.0-py2.7.egg/theano/scan_module/scan_opt.py
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 6 -> /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13/lib/python2.7/site-packages/Theano-0.9.0-py2.7.egg/theano/tensor/__init__.py
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 7 -> /camp/apps/eb/intel-2017a/software/Theano/0.9.0-intel-2017a-Python-2.7.13/lib/python2.7/site-packages/Theano-0.9.0-py2.7.egg/theano/tensor/io.py
lr-x------ 1 huffmaa domain_users 64 May 30 17:17 8 -> /camp/apps/eb/intel-2017a/software/Python/2.7.13-intel-2017a/lib/python2.7/site-packages/mpi4py/MPI.so
```

Again nothing from `strace`.

**Comment by gppezzi** [comment]
Is the mpi subsystem enabled on the login nodes? 

If not, you could try to add `--no-test-load` in order to install [Rmpi](https://github.com/eth-cscs/production/blob/6f68790528cd94d9b49540e8e9c7a0179253d666/easybuild/easyblocks/rmpi.py#L86)..

I had a similar problem with theano, it uses mpi4py and I had to [skip sanity checks](https://github.com/eth-cscs/production/blob/1f2b209679596f4c1005393513b25a8225b48603/easybuild/easyconfigs/t/Theano/Theano-0.8.2-CrayGNU-2016.03-Python-2.7.11.eb#L24).

**Comment by boegel** [comment]
Fixed with #4623?

**Comment by verdurin** [comment]
No, still hanging in the same way for me.

I'm running the build from a compute node that is MPI-enabled.
